server:
  port: 1000
  servlet:
    context-path: /auth-server
security:
  oauth2:
    client:
      client-id: storybox
      client-secret: storybox-super-secure
      authorized-grant-types: refresh_token,password,client_credentials,authorization_code
      scope: read, write

#spring.security.user.name=simple
#spring.security.user.password=simplesecure
#spring.security.user.roles=USER